# Generated by Django 3.2.7 on 2021-09-26 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_aula', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano_de_aula',
            name='revisao',
        ),
    ]
