# Generated by Django 3.2.7 on 2021-09-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_auto_20210930_2130'),
        ('plano_de_aula', '0004_remove_plano_de_aula_revisao'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano_de_aula',
            name='revisao',
            field=models.ManyToManyField(to='cadastro.Revisao', verbose_name='Revisões'),
        ),
    ]
