# Generated by Django 3.2.7 on 2021-09-30 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_auto_20210930_2130'),
        ('plano_de_aula', '0005_plano_de_aula_revisao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano_de_aula',
            name='revisao',
        ),
        migrations.AddField(
            model_name='plano_de_aula',
            name='revisao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro.revisao', verbose_name='Revisões'),
            preserve_default=False,
        ),
    ]
