# Generated by Django 3.2.7 on 2021-09-30 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_aula', '0006_auto_20210930_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano_de_aula',
            name='revisao',
        ),
        migrations.CreateModel(
            name='Revisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisao', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Revisão')),
                ('ativo', models.BooleanField(default=True)),
                ('plano_de_aula', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plano_de_aula.plano_de_aula', verbose_name='Planos de Aulas')),
            ],
            options={
                'verbose_name': 'Revisão',
                'verbose_name_plural': 'Revisões',
            },
        ),
    ]
