# Generated by Django 3.2.7 on 2021-09-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_aula', '0007_auto_20210930_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano_de_aula',
            name='observacao',
            field=models.TextField(default=1, max_length=1000, verbose_name='Observação'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Revisao',
        ),
    ]
