# Generated by Django 3.2.7 on 2021-09-25 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisao1', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Primeira Revisão')),
                ('revisao2', models.PositiveIntegerField(blank=True, default=7, null=True, verbose_name='Segunda Revisão')),
                ('revisao3', models.PositiveIntegerField(blank=True, default=14, null=True, verbose_name='Terceira Revisão')),
                ('revisao4', models.PositiveIntegerField(blank=True, default=30, null=True, verbose_name='Quarta Revisão')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudo', models.CharField(max_length=100, verbose_name='Estudo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro.materias', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Estudo',
                'verbose_name_plural': 'Estudos',
            },
        ),
    ]
