# Generated by Django 3.2.7 on 2021-09-26 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_estudos_revisao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revisao',
            options={'verbose_name': 'Revisão', 'verbose_name_plural': 'Revisões'},
        ),
    ]
