# Generated by Django 3.2.7 on 2021-09-30 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_revisao_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revisao',
            old_name='revisao1',
            new_name='revisao',
        ),
        migrations.RemoveField(
            model_name='revisao',
            name='revisao2',
        ),
        migrations.RemoveField(
            model_name='revisao',
            name='revisao3',
        ),
        migrations.RemoveField(
            model_name='revisao',
            name='revisao4',
        ),
    ]
