# Generated by Django 3.2.7 on 2021-09-30 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_aula', '0007_auto_20210930_2221'),
        ('cadastro', '0004_auto_20210930_2130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Revisao',
        ),
    ]
