# Generated by Django 3.2.7 on 2021-09-30 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_revisao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Revisao',
        ),
    ]
