# Generated by Django 3.2.7 on 2021-09-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_delete_revisao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materias',
            name='materia',
            field=models.CharField(max_length=30, unique=True, verbose_name='Materia'),
        ),
    ]
